# name: CI

# on:
#   push:
#     branches:
#       - "**"

# jobs:
#   build:
#     runs-on: ["self-hosted", "linux", "x64"]

#     strategy:
#       matrix:
#         node-version: [12.x]

#     steps:
#       - uses: actions/checkout@v2
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v1
#         with:
#           node-version: ${{ matrix.node-version }}

#       - name: Run npm install, and lint
#         run: |
#           npm install
#           npm run lint
